language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-numpy python-scipy
  - sudo apt-get install -qq libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
  - (cd ; test -e distributions || git clone git@github.com:forcedotcom/distributions)
  - (cd $HOME/distributions ; git pull)
  - make -C $HOME/distributions install
cache:
  directories:
  - $HOME/distributions
env:
  - $DISTRIBUTIONS_PATH="$HOME/distributions"
  - CXX_FLAGS="-march=native"
install:
  - make install
  - pip freeze
script:
  - make test
