language: python
python:
  - 2.7
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
virtualenv:
  system_site_packages: true
before_install:
  - export CLONE=$PWD
  - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH
  - export MAKEFLAGS="-j 2 -S"
  - export THREADS=2
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-setuptools cython python-numpy python-scipy libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
  - cd
  - rm -rf distributions
  - git clone https://github.com/forcedotcom/distributions.git
  - cd distributions
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - DISTRIBUTIONS_USE_PROTOBUF=1 make install
  - cd $CLONE
install:
  - make install
  - pip freeze
script:
  - NOSE_PROCESSES=0 make test
