language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
cache:
  apt: true
  bundler: true
  directories:
  - $HOME/.pip-cache
  - $HOME/distributions
  - build
  - data
before_install:
  - export CLONE=$PWD
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-numpy python-scipy
  - sudo apt-get install -qq libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
  - cd
  - test -e distributions || git clone https://github.com/forcedotcom/distributions.git
  - cd distributions
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - git pull
  - make install
  - cd $CLONE
env:
  - DISTRIBUTIONS_PATH="$HOME/distributions" CXX_FLAGS="-march=native"
install:
  - make install
  - pip freeze
script:
  - make test
