language: python
python:
  - 2.7
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
  - $HOME/distributions
  - data
virtualenv:
  system_site_packages: true
before_install:
  - export CLONE=$PWD
  - export MAKEFLAGS="-j $(python -c 'from multiprocessing import cpu_count; print cpu_count()')"
  - echo Building on $MAKEFLAGS cpus
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-numpy python-scipy
  - sudo apt-get install -qq libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
  - cd
  - test -e distributions || git clone https://github.com/forcedotcom/distributions.git
  - cd distributions
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - git pull
  - DISTRIBUTIONS_USE_PROTOBUF=1 make install
  - cd $CLONE
env:
  - CXX_FLAGS="-march=native"
install:
  - make install
  - pip freeze
script:
  - make test
