language: python
python:
  - 2.7
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
virtualenv:
  system_site_packages: true
before_install:
  - export CLONE=$PWD
  - export MAKEFLAGS="-j $(python -c 'from multiprocessing import cpu_count; print cpu_count()')"
  - echo Building on $MAKEFLAGS cpus
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-setuptools cython python-numpy python-scipy libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
  - cd
  - rm -rf distributions
  - git clone https://github.com/forcedotcom/distributions.git
  - cd distributions
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - python -c 'import distutils as m; print m.__version__'
  - python -c 'import setuptools as m; print m.__version__'
  - python -c 'import cython as m; print m.__version__'
  - make install
  - cd $CLONE
env:
  - DISTRIBUTIONS_PATH="$HOME/distributions" CXX_FLAGS="-march=native"
install:
  - make install
  - pip freeze
script:
  - make test
